### ISSUE TITLE
Podman page not syncronized

### ISSUE THREAD

**Issue by leleobhz** [SelfhostedPro/Yacht-Docs#24]
Hello!

https://yacht.sh/docs/Installation/Podman at momment I open this ticket does not reflect https://github.com/SelfhostedPro/Yacht-Docs/blob/master/docs/Installation/podman.md and the podman syntax is wrong on oficial site.

![image](https://user-images.githubusercontent.com/201189/228835533-ae9f7177-6333-4411-8aba-6205eafeb22e.png)

Its possible to sync it again?

**Comment by wickedyoda** [comment]
Currently working on updating the docs

**Comment by wickedyoda** [comment]
Check out dev.yacht.sh, we are working to get it synced to yacht.sh but right now the updates are pushed to an alt host, dev.yacht.sh. @leleobhz
