### ISSUE TITLE
Podman installation missing --name value

### ISSUE THREAD

**Issue by tseaward** [SelfhostedPro/Yacht-Docs#8]
On [this](https://yacht.sh/docs/Installation/Podman) page the command for starting Yacht is massing a value for the `--name` argument. This results in the command failing.

```bash
podman run -v /var/run/podman/podman.sock:/var/run/docker.sock -v yacht:/config -p 8000:8000 --name -d ghcr.io/selfhostedpro/yacht:latest
```

Solution: add a value, e.g.  as per [this](https://yacht.sh/docs/Installation/Install) page.

```bash
podman run -v /var/run/podman/podman.sock:/var/run/docker.sock -v yacht:/config -p 8000:8000 --name yacht -d ghcr.io/selfhostedpro/yacht:latest
```

**Comment by SelfhostedPro** [comment]
Ah, thanks! I'll add that shortly.
